version: '3.8'

services:
  mysql_test:
    image: mysql:8.0
    restart: always

    environment:
      MYSQL_DATABASE: test_cars_01
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - "3307"
    networks:
      - cars-01-network
    volumes:
      - "./persistence/data/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./persistence/data/data.sql:/docker-entrypoint-initdb.d/2.sql"

  mysql_main:
    image: mysql:8.0
    restart: always

    environment:
      MYSQL_DATABASE: cars_01
      MYSQL_ROOT_PASSWORD: main
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    networks:
      - cars-01-network
    volumes:
      - "mysql_cars_01:/var/lib/mysql"
      - "./api/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql"

  cars_01_web_app:
    image: pietrasfilip/cars-01-app:1.0
    ports:
      - "8080:8080"
    restart: always
    networks:
      - cars-01-network

volumes:
  mysql_test:
  mysql_cars_01:
  cars_01_web_app:
networks:
  cars-01-network: